Updating app to use new re-ignited app structure
slackapi/deno-incident-management pull request #9
Opened 2022-04-20 19:28 UTC by filmaj

###  Summary

Tried this with the latest CLI revision, seems to work!

2022-04-20 20:56 UTC, mwbrooks reviewed
Impressive @filmaj! You've set the bar for all of us to update our track apps too! I haven't run this locally yet, but wanted to leave a quick comment about dependencies

2022-04-20 20:56 UTC, mwbrooks commented on import_map.json
> +    "deno-slack-api/": "https://deno.land/x/deno_slack_api@0.0.2/"
Just curious, can [dependabot](https://github.com/dependabot) check these type of dependencies?

2022-04-20 21:03 UTC, shapirone requested changes
This is awesome to see! Seems like there's still some cleanup that might need to happen from the old app model, in particular this branch still has the old `project.ts` file and I assume we want to make sure that's no longer there.

2022-04-20 21:47 UTC, filmaj commented on functions/create_incident.ts
> +  const env: any = args.env;
Hmm maybe it's my IDE but deno's linter most definitely didn't like it when I didn't type the de-referenced args.

UPDATE: wtf I reverted back to dereferenced args and it was no big deal... ooook... I will update this 😄 thanks for pointing it out

2022-04-20 21:53 UTC, shapirone commented on functions/create_incident.ts
> +  const env: any = args.env;
FWIW I know I need to kick VSCode a bit when touching/changing versions. I do that by either using `Deno: Restart Language Server` or `Deno: Reload Import Registries Cache`

2022-04-20 21:55 UTC, filmaj commented on functions/create_incident.ts
> +  const env: any = args.env;
_resist... mentioning... `vim`... must... resist.... failure_

2022-04-21 14:41 UTC, filmaj commented on import_map.json
> +    "deno-slack-api/": "https://deno.land/x/deno_slack_api@0.0.2/"
Nope, [not yet](https://github.com/dependabot/dependabot-core/issues/2417).

2022-04-21 15:13 UTC, filmaj commented
@shapirone thanks for the review! I believe I've addressed your comments now.

2022-04-21 15:30 UTC, filmaj commented on functions/create_incident.ts
> +import { paramCase } from "https://deno.land/x/case@2.1.1/mod.ts";
So I initially moved this into a top-level `deps.ts` file to house external dependencies, but that made [updating the tutorial track on our docs](https://api.slack.com/tutorials/tracks/create-incident) site way more complex than it needed to be, for a single external dependency. So, I settled on embedding the dependency URL directly in the code, as this is the only place we use it.

2022-04-22 17:54 UTC, jesselawson commented on functions/create_incident.ts
> +  // Tweak the channel name to conform to naming requirements.
Since this is going to be open source, do you think it would be beneficial to flesh out this comment a bit more to explain why we're using paramCase here? I know it turns a "string like this" into a "string-like-this" -- but for someone who hasn't used that before, we ought to avoid them having to go out and look something up.

2022-04-22 20:08 UTC, filmaj commented on functions/create_incident.ts
> +  // Tweak the channel name to conform to naming requirements.
I believe I've resolved this!

2022-04-22 20:30 UTC, srajiang reviewed
@filmaj @shapirone @mwbrooks 
Should we consider moving this app once finalized (for reignite) into Slack Samples repo and directing those brave few who want to try it out to get it from there? Could be a good opportunity to start bumping the official home of Slack Samples.

2022-04-22 22:11 UTC, jesselawson commented
> @filmaj @shapirone @mwbrooks @jesselawson Should we consider moving this app once finalized into Slack Samples org and directing those brave few who want to try it out to get it from there? Could be a good opportunity to start bumping the official home of Slack Samples.

If we're going to do it, now is the time to do it!

2022-04-22 23:16 UTC, mwbrooks commented
> @filmaj @shapirone @mwbrooks @jesselawson Should we consider moving this app once finalized into Slack Samples org and directing those brave few who want to try it out to get it from there? Could be a good opportunity to start bumping the official home of Slack Samples.

Good idea. Let's move each app to the Sample's org as it's updated to the re-ignite app structure. GitHub URLs will redirect both git clone and browser visits, so it's an easy transition.

2023-03-17 18:57 UTC, misscoded commented
@filmaj I think we can close this at this point, correct?

2023-03-23 21:28 UTC, misscoded commented
@filmaj I think so! And we have the PE version still living on in its PE home. I leave the honors to you. 😅

2023-03-24 12:38 UTC, closed without merging